language: c

os: linux
dist: xenial

compiler:
  - gcc

cache:
  ccache: true
  directories:
  - ${TRAVIS_BUILD_DIR}/download

before_install:
  - sudo update-alternatives --set awk /usr/bin/gawk
  - ccache --version
  - make --version
  - unset CC
  - ccache -M 16G && ccache -z

before_script:
  - maketarget='gcc gdb'; [ -z ${pbsarch} ] && maketarget='tools' || true
  - testtarget='compiler-test'; [ -z ${pbsarch} ] && testtarget='tools-test' || true
  - echo "maketarget = $maketarget"
  - echo "testtarget = $testtarget"

script:
  - make TARGET=${pbsarch} $maketarget >"${TRAVIS_BUILD_DIR}/build.log"
  - '[ -z ${pbsarch} ] || make TARGET=${pbsarch} qemu >"${TRAVIS_BUILD_DIR}/build-qemu.log"'
  - make TARGET=${pbsarch} $testtarget

after_success:
  - ccache -s

after_failure:
  - echo "===== Last 100 lines of build.log ====="
  - tail -n100 "${TRAVIS_BUILD_DIR}/build.log"
  - echo "===== =========================== ====="
  - echo "===== Last 100 lines of build-qemu.log ====="
  - '[ -f "${TRAVIS_BUILD_DIR}/build-qemu.log" ] && tail -n100 "${TRAVIS_BUILD_DIR}/build-qemu.log"'
  - echo "===== ================================ ====="

env:
  - pbsarch=''
  - pbsarch=aarch64-unknown-linux-gnu
  - pbsarch=aarch64-unknown-linux-uclibc
  - pbsarch=alpha-linux-gnu
  - pbsarch=arm-unknown-linux-gnueabi
  - pbsarch=arm-unknown-linux-uclibceabi
  - pbsarch=armv7l-unknown-linux-gnueabihf
  - pbsarch=armv7l-unknown-linux-uclibceabihf
  - pbsarch=armv8a-unknown-linux-gnueabihf
  - pbsarch=i786-pc-linux-gnu
  - pbsarch=i786-pc-linux-uclibc
  - pbsarch=m68k-linux-gnu
  - pbsarch=mipsel-linux-gnu
  - pbsarch=mips-linux-gnu
  - pbsarch=powerpc-unknown-linux-gnu
  - pbsarch=powerpc-unknown-linux-uclibc
  - pbsarch=s390-linux-gnu
  - pbsarch=sh4-linux-gnu
  - pbsarch=sparc64-linux-gnu
  - pbsarch=x86_64-unknown-linux-gnu
