language: c

sudo: required
dist: trusty

compiler:
  - gcc

cache:
  directories:
  - $HOME/pbs-stage1/build/autoconf-*
  - $HOME/pbs-stage1/build/automake-*
  - $HOME/pbs-stage1/build/ccache-*
  - $HOME/pbs-stage1/build/gmp-*
  - $HOME/pbs-stage1/build/libtool-*
  - $HOME/pbs-stage1/build/m4-*
  - $HOME/pbs-stage1/build/mpc-*
  - $HOME/pbs-stage1/build/mpfr-*
  - $HOME/pbs-stage1/build/ncurses-*
  - $HOME/pbs-stage1/build/pkg-config-*
  - $HOME/pbs-stage1/build/ppl-*
  - $HOME/pbs-stage1/build/stamp/extract-autoconf-*
  - $HOME/pbs-stage1/build/stamp/extract-automake-*
  - $HOME/pbs-stage1/build/stamp/extract-ccache-*
  - $HOME/pbs-stage1/build/stamp/extract-m4-*
  - $HOME/pbs-stage1/build/stamp/extract-mpc-*
  - $HOME/pbs-stage1/build/stamp/extract-mpfr-*
  - $HOME/pbs-stage1/build/stamp/extract-ncurses-*
  - $HOME/pbs-stage1/build/stamp/extract-pkg-config-*
  - $HOME/pbs-stage1/build/stamp/extract-ppl-*
  - $HOME/pbs-stage1/build/stamp/apply-ncurses-*
  - $HOME/pbs-stage1/meta/_host-check
  - $HOME/pbs-stage1/meta/autoconf
  - $HOME/pbs-stage1/meta/autoconf-archive
  - $HOME/pbs-stage1/meta/automake
  - $HOME/pbs-stage1/meta/ccache
  - $HOME/pbs-stage1/meta/gmp
  - $HOME/pbs-stage1/meta/libtool
  - $HOME/pbs-stage1/meta/m4
  - $HOME/pbs-stage1/meta/mpc
  - $HOME/pbs-stage1/meta/mpfr
  - $HOME/pbs-stage1/meta/ncurses
  - $HOME/pbs-stage1/meta/pkg-config
  - $HOME/pbs-stage1/meta/ppl
  - $HOME/pbs-stage1/bin
  - $HOME/pbs-stage1/include
  - $HOME/pbs-stage1/lib
  - $HOME/pbs-stage1/share
  - $HOME/pbs-stage1/tests

before_install:
  - sudo update-alternatives --set awk /usr/bin/gawk
  - sudo apt-get install help2man
  - |
    wget https://ftp.gnu.org/gnu/make/make-3.82.tar.gz
    tar xf make-3.82.tar.gz && cd make-3.82
    ./configure && make -j && sudo make install
    cd .. && rm -rf make-3.82
  - test -f /usr/local/bin/make && sudo mv /usr/bin/make /usr/bin/make-3.81 &&
    sudo ln -s /usr/local/bin/make /usr/bin
  - make --version
  - unset CC

before_script:
  - make

script: make -s --no-print-directory TARGET=${pbsarch} 1>build.log

after_script: echo -e "\n\n\n\tPOST-MORTEM stdout\n" && tail -n 2000 build.log

env:
  - pbsarch=''
  - pbsarch=aarch64-unknown-linux-gnu
  - pbsarch=aarch64-unknown-linux-uclibc
  - pbsarch=alpha-linux-gnu
  - pbsarch=arm-unknown-linux-gnueabi
  - pbsarch=arm-unknown-linux-uclibceabi
  - pbsarch=armv7l-unknown-linux-gnueabihf
  - pbsarch=armv7l-unknown-linux-uclibceabihf
  - pbsarch=i786-pc-linux-gnu
  - pbsarch=i786-pc-linux-uclibc
  - pbsarch=ia64-unknown-linux-gnu
  - pbsarch=m68k-linux-gnu
  - pbsarch=mipsel-linux-gnu
  - pbsarch=mips-linux-gnu
  - pbsarch=powerpc-unknown-linux-gnu
  - pbsarch=powerpc-unknown-linux-uclibc
  - pbsarch=s390-linux-gnu
  - pbsarch=sh4-linux-gnu
  - pbsarch=sparc64-linux-gnu
  - pbsarch=x86_64-unknown-linux-gnu
